# This file was generated by GoReleaser. DO NOT EDIT.
cask "chain-rpc" do
  desc "Fast CLI tool for finding public RPC endpoints for blockchain networks"
  homepage "https://github.com/nksazonov/chain-rpc"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chain-rpc"

  on_macos do
    on_intel do
      url "https://github.com/nksazonov/chain-rpc/releases/download/v0.1.2/chain-rpc-0.1.2-darwin-amd64.tar.gz"
      sha256 "8c58261fadc6a8347ccaf45ea17fba5d691ec5bf9cb4d190611501104dd1e690"
    end
    on_arm do
      url "https://github.com/nksazonov/chain-rpc/releases/download/v0.1.2/chain-rpc-0.1.2-darwin-arm64.tar.gz"
      sha256 "fdf6543bd8c1cea0a220c578a405720645fe6b883493e41b90f0fabb0d1ca890"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nksazonov/chain-rpc/releases/download/v0.1.2/chain-rpc-0.1.2-linux-amd64.tar.gz"
      sha256 "ec5c009e0338b7afa95b2b14c8da8b47a6068dd2ead6813b0d675cbe3d647f32"
    end
    on_arm do
      url "https://github.com/nksazonov/chain-rpc/releases/download/v0.1.2/chain-rpc-0.1.2-linux-arm64.tar.gz"
      sha256 "96bc7b666688b680555c9405fb65452785a99613a920660686b347a5a7b3c91e"
    end
  end

  # No zap stanza required
end
