# This file was generated by GoReleaser. DO NOT EDIT.
cask "chain-rpc" do
  version "0.1.1"

  name "chain-rpc"
  desc "Fast CLI tool for finding public RPC endpoints for blockchain networks"
  homepage "https://github.com/nksazonov/chain-rpc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chain-rpc"

  on_macos do
    on_intel do
      sha256 "f6b7ebf4156a5a4b9946aaf00815d1e828fee8a5105b7985d9b0fc3785451068"
      url "https://github.com/nksazonov/chain-rpc/releases/download/v0.1.1/chain-rpc-0.1.1-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "f37b7fed119bea7315780281377542d41f390b62511755d831db26ae561503db"
      url "https://github.com/nksazonov/chain-rpc/releases/download/v0.1.1/chain-rpc-0.1.1-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f3a8fe85e0addeaf9972613424901f2e601e9a34d3e2ff73c8ce7739759737ca"
      url "https://github.com/nksazonov/chain-rpc/releases/download/v0.1.1/chain-rpc-0.1.1-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "b2fb3d92e5438522f9bed5699aeaa5c026e90744c709cf2e0024cf6d3d5ff51b"
      url "https://github.com/nksazonov/chain-rpc/releases/download/v0.1.1/chain-rpc-0.1.1-linux-arm64.tar.gz"
    end
  end

  # No zap stanza required
end
